-- fixing … to ...
UPDATE Track SET Title = 'One Step Beyond...' WHERE Id = 2274;

-- fixing ’ to '
UPDATE Track SET Title = 'I''m Gonna Knock On Your Door' WHERE Id = 1390;
UPDATE Track SET Title = 'I''m So Excited' WHERE Id = 1391;
UPDATE Track SET Title = 'Let''s All Chant' WHERE Id = 1779;
UPDATE Track SET Title = 'Walk-Don''t Run' WHERE Id = 3352;

-- fixing ´ to '
UPDATE Track SET Title = 'I''m a Man' WHERE Id = 1389;

-- Adding search column for tracks with special characters
UPDATE Track SET SearchArtist = 'Raffaela Carra' WHERE Id = 51;
UPDATE Track SET SearchArtist = 'BLOF' WHERE Id = 79;
UPDATE Track SET SearchArtist = 'Rene Froger' WHERE Id = 159;
UPDATE Track SET SearchArtist = 'Freddie Mercury & Montserrat Caballe' WHERE Id = 295;
UPDATE Track SET SearchTitle = 'Belgie' WHERE Id = 323;
UPDATE Track SET SearchArtist = 'Rowwen Heze' WHERE Id = 333;
UPDATE Track SET SearchTitle = 'Bourree' WHERE Id = 411;
UPDATE Track SET SearchArtist = 'Anneke Gronloh' WHERE Id = 414;
UPDATE Track SET SearchArtist = 'Hollenboer' WHERE Id = 446;
UPDATE Track SET SearchTitle = 'Con Te Partiro' WHERE Id = 560;
UPDATE Track SET SearchArtist = 'Andre Hazes' WHERE Id = 654;
UPDATE Track SET SearchTitle = 'Eres Tu' WHERE Id = 828;
UPDATE Track SET SearchArtist = 'Herbert Gronemeyer' WHERE Id = 1082;
UPDATE Track SET SearchTitle = 'He kom aan' WHERE Id = 1114;
UPDATE Track SET SearchTitle = 'Het Kleine Cafe Aan De Haven' WHERE Id = 1166;
UPDATE Track SET SearchTitle = 'Il Est Cinq Heures Paris S''Eveille' WHERE Id = 1450;
UPDATE Track SET SearchTitle = 'La Poupee Qui Fait Non' WHERE Id = 1713;
UPDATE Track SET SearchTitle = 'Le Meteque' WHERE Id = 1755;
UPDATE Track SET SearchTitle = 'Les Champs-Elysees' WHERE Id = 1768;
UPDATE Track SET SearchTitle = 'L''Ete Indien' WHERE Id = 1780;
UPDATE Track SET SearchArtist = 'BLOF' WHERE Id = 1800;
UPDATE Track SET SearchArtist = 'Rowwen Heze' WHERE Id = 1816;
UPDATE Track SET SearchTitle = 'Ma preference' WHERE Id = 1941;
UPDATE Track SET SearchTitle = 'Maria Elena' WHERE Id = 1988;
UPDATE Track SET SearchArtist = 'Rene Klijn' WHERE Id = 2100;
UPDATE Track SET SearchTitle = 'Musica E' WHERE Id = 2114;
UPDATE Track SET SearchArtist = 'Celine Dion' WHERE Id = 2127;
UPDATE Track SET SearchArtist = 'Andre Hazes' WHERE Id = 2143;
UPDATE Track SET SearchArtist = 'Andre Hazes' WHERE Id = 2144;
UPDATE Track SET SearchTitle = 'Non Non Rien N''A Change' WHERE Id = 2208;
UPDATE Track SET SearchTitle = 'Ole guapa' WHERE Id = 2245;
UPDATE Track SET SearchArtist = 'Leen Jongewaard & Andre van den Heuvel' WHERE Id = 2289;
UPDATE Track SET SearchTitle = 'Poupee de cire, poupee de son' WHERE Id = 2389;
UPDATE Track SET SearchArtist = 'Celine Dion' WHERE Id = 2391;
UPDATE Track SET SearchArtist = 'Celine Dion & Barbra Streisand' WHERE Id = 2950;
UPDATE Track SET SearchArtist = 'Celine Dion' WHERE Id = 3068;
UPDATE Track SET SearchArtist = 'Celine Dion' WHERE Id = 3138;
UPDATE Track SET SearchArtist = 'Rene Froger' WHERE Id = 3145;
UPDATE Track SET SearchArtist = 'Francoise Hardy', SearchTitle = 'Tous les garcons et les filles' WHERE Id = 3218;
UPDATE Track SET SearchArtist = 'Andre van Duin' WHERE Id = 3505;
UPDATE Track SET SearchArtist = 'Andre van Duin' WHERE Id = 171;
UPDATE Track SET SearchTitle = 'Apres Toi' WHERE Id = 218;
UPDATE Track SET SearchArtist = 'Danyel Gerard' WHERE Id = 448;
UPDATE Track SET SearchTitle = 'Comment ca va' WHERE Id = 558;
UPDATE Track SET SearchTitle = 'Helene' WHERE Id = 1133;
UPDATE Track SET SearchArtist = 'Andre Hazes' WHERE Id = 3653;
UPDATE Track SET SearchArtist = 'Celine Dion' WHERE Id = 314;
UPDATE Track SET SearchArtist = 'C. Jerome' WHERE Id = 502;
UPDATE Track SET SearchArtist = 'Andre Hazes' WHERE Id = 680;
UPDATE Track SET SearchArtist = 'BLOF' WHERE Id = 1098;
UPDATE Track SET SearchTitle = 'Sajang E' WHERE Id = 2571;
UPDATE Track SET SearchArtist = 'Andre Rieu' WHERE Id = 2610;
UPDATE Track SET SearchArtist = 'BLOF' WHERE Id = 3370;
UPDATE Track SET SearchTitle = 'Wer Bisto' WHERE Id = 3403;
UPDATE Track SET SearchArtist = 'Andre Hazes' WHERE Id = 1439;
UPDATE Track SET SearchArtist = 'BLOF' WHERE Id = 376;
UPDATE Track SET SearchArtist = 'BLOF' WHERE Id = 623;
UPDATE Track SET SearchArtist = 'Andre Hazes' WHERE Id = 806;
UPDATE Track SET SearchArtist = 'BLOF' WHERE Id = 2074;
UPDATE Track SET SearchArtist = 'Andre Hazes' WHERE Id = 3660;
UPDATE Track SET SearchArtist = 'Andre van Duin' WHERE Id = 651;
UPDATE Track SET SearchArtist = 'Andre van Duin' WHERE Id = 757;
UPDATE Track SET SearchArtist = 'Counting Crows & BLOF' WHERE Id = 1209;
UPDATE Track SET SearchArtist = 'Andre van Duin' WHERE Id = 349;
UPDATE Track SET SearchArtist = 'Rowwen Heze' WHERE Id = 647;
UPDATE Track SET SearchArtist = 'Herbert Gronemeyer' WHERE Id = 676;
UPDATE Track SET SearchArtist = 'Paul de Leeuw & Andre Hazes' WHERE Id = 783;
UPDATE Track SET SearchArtist = 'Michael Buble' WHERE Id = 893;
UPDATE Track SET SearchArtist = 'Andre Hazes' WHERE Id = 968;
UPDATE Track SET SearchArtist = 'Michael Buble' WHERE Id = 1216;
UPDATE Track SET SearchArtist = 'Celine Dion' WHERE Id = 1471;
UPDATE Track SET SearchArtist = 'Celine Dion' WHERE Id = 1498;
UPDATE Track SET SearchArtist = 'Andre Hazes' WHERE Id = 1681;
UPDATE Track SET SearchArtist = 'Anneke Gronloh' WHERE Id = 2328;
UPDATE Track SET SearchArtist = 'Andre Hazes' WHERE Id = 1165;
UPDATE Track SET SearchTitle = 'J''m''attendais pas a toi' WHERE Id = 1617;
UPDATE Track SET SearchArtist = 'BLOF' WHERE Id = 2247;
UPDATE Track SET SearchArtist = 'BLOF' WHERE Id = 80;
UPDATE Track SET SearchArtist = 'Blue Oyster Cult' WHERE Id = 720;
UPDATE Track SET SearchArtist = 'Michael Buble' WHERE Id = 859;
UPDATE Track SET SearchArtist = 'BLOF' WHERE Id = 1151;
UPDATE Track SET SearchArtist = 'Michael Buble' WHERE Id = 1875;
UPDATE Track SET SearchArtist = 'Alizee' WHERE Id = 2063;
UPDATE Track SET SearchArtist = 'BLOF' WHERE Id = 158;
UPDATE Track SET SearchArtist = 'Rowwen Heze' WHERE Id = 238;
UPDATE Track SET SearchArtist = 'Andre Hazes' WHERE Id = 382;
UPDATE Track SET SearchArtist = 'BLOF' WHERE Id = 800;
UPDATE Track SET SearchArtist = 'Daniel Lohues' WHERE Id = 1182;
UPDATE Track SET SearchArtist = 'Bjork' WHERE Id = 1566;
UPDATE Track SET SearchArtist = 'BLOF' WHERE Id = 2241;
UPDATE Track SET SearchArtist = 'Queensryche' WHERE Id = 2678;
UPDATE Track SET SearchArtist = 'Michael Buble' WHERE Id = 1111;
UPDATE Track SET SearchArtist = 'Rowwen Heze' WHERE Id = 2223;
UPDATE Track SET SearchArtist = 'BLOF' WHERE Id = 334;
UPDATE Track SET SearchArtist = 'BLOF' WHERE Id = 1234;
UPDATE Track SET SearchArtist = 'Michel Telo' WHERE Id = 107;
UPDATE Track SET SearchTitle = 'Balada (Tche Tcherere Tche Tche)' WHERE Id = 286;
UPDATE Track SET SearchArtist = 'Beyonce' WHERE Id = 1080;
UPDATE Track SET SearchArtist = 'BLOF' WHERE Id = 1740;
UPDATE Track SET SearchArtist = 'BLOF' WHERE Id = 2013;
UPDATE Track SET SearchArtist = 'Emeli Sande' WHERE Id = 2178;
UPDATE Track SET SearchTitle = 'Sovereign Light Cafe' WHERE Id = 2772;
UPDATE Track SET SearchArtist = 'BLOF' WHERE Id = 3665;
UPDATE Track SET SearchArtist = 'Emili Sande' WHERE Id = 3685;
UPDATE Track SET SearchArtist = 'Labrinth & Emeli Sande' WHERE Id = 3707;
UPDATE Track SET SearchArtist = 'Rowwen Heze' WHERE Id = 3730;
UPDATE Track SET SearchArtist = 'Lange Frans & The Lau' WHERE Id = 3808;
UPDATE Track SET SearchArtist = 'Beyonce' WHERE Id = 3817;
UPDATE Track SET SearchArtist = 'Motorhead' WHERE Id = 3831;
UPDATE Track SET SearchArtist = 'Beyonce' WHERE Id = 3838;
UPDATE Track SET SearchArtist = 'Beyonce & Jay-Z' WHERE Id = 3849;
UPDATE Track SET SearchArtist = 'BLOF' WHERE Id = 3856;
UPDATE Track SET SearchArtist = 'BLOF' WHERE Id = 3860;
UPDATE Track SET SearchArtist = 'Emeli Sande' WHERE Id = 3934;
UPDATE Track SET SearchArtist = 'Beyonce' WHERE Id = 3997;
UPDATE Track SET SearchArtist = 'Beyonce' WHERE Id = 4004;
UPDATE Track SET SearchTitle = 'Naive' WHERE Id = 4013;
UPDATE Track SET SearchArtist = 'Daniel Lohues' WHERE Id = 4022;
UPDATE Track SET SearchArtist = 'BLOF' WHERE Id = 4024;
UPDATE Track SET SearchArtist = 'Beyonce' WHERE Id = 4038;
UPDATE Track SET SearchArtist = 'Axwell /\ Ingrosso' WHERE Id = 4056;
UPDATE Track SET SearchArtist = 'Bjork' WHERE Id = 4273;
UPDATE Track SET SearchTitle = 'Nur Getraumt' WHERE Id = 4288;
UPDATE Track SET SearchArtist = 'Bokkers' WHERE Id = 4295;
UPDATE Track SET SearchArtist = 'Blof ft. Geike' WHERE Id = 4320;
UPDATE Track SET SearchTitle = 'Comptine D''Un Autre Ete: L''Apres-Midi (Amelie)' WHERE Id = 4369;
UPDATE Track SET SearchTitle = 'Major Tom (Vollig Losgelost)' WHERE Id = 4392;
UPDATE Track SET SearchArtist = 'Andre Hazes' WHERE Id = 4466;
UPDATE Track SET SearchArtist = 'Blof' WHERE Id = 4473;
UPDATE Track SET SearchTitle = 'Reunie' WHERE Id = 4498;
UPDATE Track SET SearchArtist = 'Rowwen Heze' WHERE Id = 4511;
UPDATE Track SET SearchArtist = 'Rowwen Heze' WHERE Id = 4526;
UPDATE Track SET SearchTitle = 'Senorita' WHERE Id = 4554;
UPDATE Track SET SearchTitle = 'La Boheme' WHERE Id = 4589;
UPDATE Track SET SearchTitle = 'Voila' WHERE Id = 4595;
UPDATE Track SET SearchArtist = 'Maneskin' WHERE Id = 4604;
UPDATE Track SET SearchArtist = 'Celine Dion' WHERE Id = 4613;
UPDATE Track SET SearchArtist = 'Bokkers' WHERE Id = 4619;
UPDATE Track SET SearchArtist = 'Tiesto' WHERE Id = 4624;
UPDATE Track SET SearchArtist = 'Andre Hazes' WHERE Id = 4630;
UPDATE Track SET SearchArtist = 'Andre van Duin' WHERE Id = 4636;
UPDATE Track SET SearchArtist = 'De Hunekop ft. Oele Plop', SearchTitle = 'Wy kam fram Fryslan' WHERE Id = 4667;
UPDATE Track SET SearchArtist = 'Andre Hazes' WHERE Id = 4707;
UPDATE Track SET SearchArtist = 'Maneskin' WHERE Id = 4712;
UPDATE Track SET SearchArtist = 'Sinead O''Connor' WHERE Id = 4740;
UPDATE Track SET SearchArtist = 'Beyonce' WHERE Id = 4745;
UPDATE Track SET SearchArtist = 'Andre Hazes & Gerard Joling' WHERE Id = 4777;
UPDATE Track SET SearchArtist = 'Oos Joos', SearchTitle = 'Bloemkole' WHERE Id = 4871;
UPDATE Track SET SearchArtist = 'S10 & BLOF' WHERE Id = 4902;